
messages:
  potions:
    started: '&fВы получили эффект &5{name}&f на &5{duration}&f сек.'
    ended: '&fДействие эффекта &5{name}&f закончилось.'

settings:
  effectsApplyEveryTicks: 10
  syncPlayerTaskDelay: 10
  useRomanNumerals: true
  
  line1: '{c}{display}&7 {value}'
  line2: '{c}{display}&7: {sign}{value}%'
  talismanLine: '&eТалисман {number}&7: &8[{c}{display}&8]'
  talismanEmptyLine: '&eТалисман &8{number}/{all}&7: &8[пусто]'

