name: BlueLib.ChestCommands
main: ru.kronos.chestcommands.Main
version: 1.0
api-version: 1.13
website: https://vk.com/id55511198
depend: [BlueLib]
commands:
  itemdatabase:
    usage: Используйте /<command>, чтобы открыть меню с предметами экипировки
    aliases: [itemdb, idb]
  decodatabase:
    usage: Используйте /<command>, чтобы открыть меню с предметами декора
    aliases: [decodb, ddb]