name: BlueLib.GamePhase
main: ru.kronos.gamephase.Main
version: 1.0
api-version: 1.13
website: https://vk.com/id55511198
depend: [BlueLib]
loadbefore: [BlueLib]
commands:
  gamephase:
    usage: Используйте /<command>
    aliases: [gphase]
    permission: gamephase.use
    permission-message: У вас нет нужных прав <permission>.